### ISSUE TITLE
Mapa_Mental

### ISSUE THREAD

**Issue by JeroRoque** [SistemasTecTlaxiaco/actividad-4-mapa-mental-calidad-de-software-JeroRoque#1]
[Gestión de la Calidad en Proyectos de Software.pdf](https://github.com/user-attachments/files/17103231/Gestion.de.la.Calidad.en.Proyectos.de.Software.pdf)

**Comment by josealfredo79** [comment]
Calificacion..????

**Comment by ferh1235** [comment]
20 bien hecho

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
